public class AbstractionExample {
  public static void main(String[] args) {
    CarImplementation carImplementation = new CarImplementation();
    carImplementation.carBreaking(); // calling the method
  }
}

// abstract class
abstract class Car {
  // one of the best example for abstraciton is vehicle breaking system I took
  // that.
  // we know how to breack, but not the mechanism of the breaking.

  abstract void carBreaking(); // no body for abstract method

}

class CarImplementation extends Car {

  @Override
  void carBreaking() {
    // let's make the body of the abstract method carBreaking
    System.out.println("Driver put the leg on the break pedal: 1");
    System.out.println("Force generated by the driver\'s leg is amplified several times by mechanical leverage: 2");
    System.out.println("Pressure is transmitted equally to all four breaks: 3 ");
    System.out
        .println("The force creates friction between break pads and disc brake rotors which is what stops the car: 4");

  }

}