import sun.audio.*;
import java.io.*;
import javax.swing.*;
import java.awt.*;
public class VirtualPiano extends javax.swing.JFrame {

    public VirtualPiano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jbCS = new javax.swing.JButton();
        jbC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jchkMusic = new javax.swing.JCheckBox();
        jchkSteel = new javax.swing.JCheckBox();
        jbDS = new javax.swing.JButton();
        jbE = new javax.swing.JButton();
        jbD = new javax.swing.JButton();
        jbFS = new javax.swing.JButton();
        jbF = new javax.swing.JButton();
        jbGS = new javax.swing.JButton();
        jbG = new javax.swing.JButton();
        jbBb = new javax.swing.JButton();
        jbA = new javax.swing.JButton();
        jbB = new javax.swing.JButton();
        jbCS1 = new javax.swing.JButton();
        jbC1 = new javax.swing.JButton();
        jbDS1 = new javax.swing.JButton();
        jbD1 = new javax.swing.JButton();
        jbF1 = new javax.swing.JButton();
        jbE1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 8));
        jPanel1.setLayout(null);

        jbCS.setBackground(java.awt.Color.black);
        jbCS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbCS.setForeground(new java.awt.Color(255, 255, 255));
        jbCS.setText("C#");
        jbCS.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCSActionPerformed(evt);
            }
        });
        jPanel1.add(jbCS);
        jbCS.setBounds(40, 150, 70, 220);

        jbC.setBackground(java.awt.Color.white);
        jbC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbC.setText("C");
        jbC.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCActionPerformed(evt);
            }
        });
        jPanel1.add(jbC);
        jbC.setBounds(30, 150, 60, 430);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Virtual Piano");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 10, 620, 80);

        buttonGroup1.add(jchkMusic);
        jchkMusic.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jchkMusic.setForeground(java.awt.Color.white);
        jchkMusic.setText("MusicNotes");
        jPanel1.add(jchkMusic);
        jchkMusic.setBounds(30, 100, 240, 40);

        buttonGroup1.add(jchkSteel);
        jchkSteel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jchkSteel.setForeground(java.awt.Color.white);
        jchkSteel.setText("Steel Drum");
        jPanel1.add(jchkSteel);
        jchkSteel.setBounds(610, 100, 230, 40);

        jbDS.setBackground(java.awt.Color.black);
        jbDS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbDS.setForeground(new java.awt.Color(255, 255, 255));
        jbDS.setText("D#");
        jbDS.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDSActionPerformed(evt);
            }
        });
        jPanel1.add(jbDS);
        jbDS.setBounds(120, 150, 70, 220);

        jbE.setBackground(java.awt.Color.white);
        jbE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbE.setText("E");
        jbE.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEActionPerformed(evt);
            }
        });
        jPanel1.add(jbE);
        jbE.setBounds(170, 150, 60, 430);

        jbD.setBackground(java.awt.Color.white);
        jbD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbD.setText("D");
        jbD.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDActionPerformed(evt);
            }
        });
        jPanel1.add(jbD);
        jbD.setBounds(100, 150, 60, 430);

        jbFS.setBackground(java.awt.Color.black);
        jbFS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbFS.setForeground(new java.awt.Color(255, 255, 255));
        jbFS.setText("F#");
        jbFS.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFSActionPerformed(evt);
            }
        });
        jPanel1.add(jbFS);
        jbFS.setBounds(270, 150, 70, 220);

        jbF.setBackground(java.awt.Color.white);
        jbF.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbF.setText("F");
        jbF.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFActionPerformed(evt);
            }
        });
        jPanel1.add(jbF);
        jbF.setBounds(260, 150, 60, 430);

        jbGS.setBackground(java.awt.Color.black);
        jbGS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbGS.setForeground(new java.awt.Color(255, 255, 255));
        jbGS.setText("G#");
        jbGS.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbGS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGSActionPerformed(evt);
            }
        });
        jPanel1.add(jbGS);
        jbGS.setBounds(350, 150, 70, 220);

        jbG.setBackground(java.awt.Color.white);
        jbG.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbG.setText("G");
        jbG.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGActionPerformed(evt);
            }
        });
        jPanel1.add(jbG);
        jbG.setBounds(330, 150, 60, 430);

        jbBb.setBackground(java.awt.Color.black);
        jbBb.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbBb.setForeground(new java.awt.Color(255, 255, 255));
        jbBb.setText("Bb");
        jbBb.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbBb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBbActionPerformed(evt);
            }
        });
        jPanel1.add(jbBb);
        jbBb.setBounds(430, 150, 70, 220);

        jbA.setBackground(java.awt.Color.white);
        jbA.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbA.setText("A");
        jbA.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAActionPerformed(evt);
            }
        });
        jPanel1.add(jbA);
        jbA.setBounds(400, 150, 60, 430);

        jbB.setBackground(java.awt.Color.white);
        jbB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbB.setText("B");
        jbB.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBActionPerformed(evt);
            }
        });
        jPanel1.add(jbB);
        jbB.setBounds(470, 150, 60, 430);

        jbCS1.setBackground(java.awt.Color.black);
        jbCS1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbCS1.setForeground(new java.awt.Color(255, 255, 255));
        jbCS1.setText("C#1");
        jbCS1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbCS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCS1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbCS1);
        jbCS1.setBounds(570, 150, 70, 220);

        jbC1.setBackground(java.awt.Color.white);
        jbC1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jbC1.setText("C1");
        jbC1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbC1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbC1);
        jbC1.setBounds(560, 150, 60, 430);

        jbDS1.setBackground(java.awt.Color.black);
        jbDS1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jbDS1.setForeground(new java.awt.Color(255, 255, 255));
        jbDS1.setText("D#1");
        jbDS1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbDS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDS1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbDS1);
        jbDS1.setBounds(650, 150, 70, 220);

        jbD1.setBackground(java.awt.Color.white);
        jbD1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jbD1.setText("D1");
        jbD1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbD1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbD1);
        jbD1.setBounds(630, 150, 60, 430);

        jbF1.setBackground(java.awt.Color.white);
        jbF1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jbF1.setText("F1");
        jbF1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbF1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbF1);
        jbF1.setBounds(780, 150, 60, 430);

        jbE1.setBackground(java.awt.Color.white);
        jbE1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jbE1.setText("E1");
        jbE1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbE1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbE1);
        jbE1.setBounds(700, 150, 60, 430);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 880, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCActionPerformed
        InputStream iAudio;
        if(jchkMusic.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\C.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jchkSteel.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\C_Drum.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbCActionPerformed

    private void jbEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEActionPerformed
        InputStream iAudio;
        if(jchkMusic.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\E.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jchkSteel.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\E_Drum.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbEActionPerformed

    private void jbCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCSActionPerformed
        InputStream iAudio;
        if(jchkMusic.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\C_s.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jchkSteel.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\Cq_Drum.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbCSActionPerformed

    private void jbDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDActionPerformed
        InputStream iAudio;
        if(jchkMusic.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\D.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jchkSteel.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\D_Drum.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbDActionPerformed

    private void jbFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFActionPerformed
        InputStream iAudio;
        if(jchkMusic.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\F.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jchkSteel.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\F_Drum.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbFActionPerformed

    private void jbFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFSActionPerformed
        InputStream iAudio;
        if(jchkMusic.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\F_s.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jchkSteel.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\Fq_Drum.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbFSActionPerformed

    private void jbGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGActionPerformed
        InputStream iAudio;
        if(jchkMusic.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\G.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jchkSteel.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\G_Drum.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbGActionPerformed

    private void jbAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAActionPerformed
        InputStream iAudio;
        if(jchkMusic.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\A.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jchkSteel.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\A_Drum.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbAActionPerformed

    private void jbBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBActionPerformed
        InputStream iAudio;
        if(jchkMusic.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\B.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jchkSteel.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\B_Drum.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbBActionPerformed

    private void jbC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbC1ActionPerformed
        InputStream iAudio;
        if(jchkMusic.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\C1.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jchkSteel.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\C1_Drum.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbC1ActionPerformed

    private void jbCS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCS1ActionPerformed
        InputStream iAudio;
        if(jchkMusic.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\C_s1.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jchkSteel.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\Cq1_Drum.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbCS1ActionPerformed

    private void jbD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbD1ActionPerformed
        InputStream iAudio;
        if(jchkMusic.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\D1.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jchkSteel.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\D1_Drum.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbD1ActionPerformed

    private void jbF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbF1ActionPerformed
        InputStream iAudio;
        if(jchkMusic.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\F1.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jchkSteel.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\F1_Drum.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbF1ActionPerformed

    private void jbE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbE1ActionPerformed
        InputStream iAudio;
        if(jchkMusic.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\E1.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jchkSteel.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\E1_Drum.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbE1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.getContentPane().setBackground(Color.BLACK);
    }//GEN-LAST:event_formWindowActivated

    private void jbDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDSActionPerformed
        InputStream iAudio;
        if(jchkMusic.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\D_s.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jchkSteel.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\Dq_Drum.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbDSActionPerformed

    private void jbGSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGSActionPerformed
        InputStream iAudio;
        if(jchkMusic.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\G_s.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jchkSteel.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\Gq_Drum.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbGSActionPerformed

    private void jbBbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBbActionPerformed
        InputStream iAudio;
        if(jchkMusic.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\Bb.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jchkSteel.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\Bb_Drum.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbBbActionPerformed

    private void jbDS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDS1ActionPerformed
        InputStream iAudio;
        if(jchkMusic.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\D_s1.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jchkSteel.isSelected()){
            try{
                iAudio = new FileInputStream((new File(".\\music notes\\Music_Note\\Dq1_Drum.wav")));
                AudioStream iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbDS1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VirtualPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VirtualPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VirtualPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VirtualPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VirtualPiano v = new VirtualPiano();
                v.setVisible(true);
                v.setBounds(200,50,940,690);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbA;
    private javax.swing.JButton jbB;
    private javax.swing.JButton jbBb;
    private javax.swing.JButton jbC;
    private javax.swing.JButton jbC1;
    private javax.swing.JButton jbCS;
    private javax.swing.JButton jbCS1;
    private javax.swing.JButton jbD;
    private javax.swing.JButton jbD1;
    private javax.swing.JButton jbDS;
    private javax.swing.JButton jbDS1;
    private javax.swing.JButton jbE;
    private javax.swing.JButton jbE1;
    private javax.swing.JButton jbF;
    private javax.swing.JButton jbF1;
    private javax.swing.JButton jbFS;
    private javax.swing.JButton jbG;
    private javax.swing.JButton jbGS;
    private javax.swing.JCheckBox jchkMusic;
    private javax.swing.JCheckBox jchkSteel;
    // End of variables declaration//GEN-END:variables
}
